import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ThemeProvider } from "./components/theme-provider";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "./components/ui/sonner";
import { SidebarProvider, SidebarTrigger } from "./components/ui/sidebar";

import { AppSidebar } from "./components/sidebar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={false}>
            <TRPCReactProvider>
              <AppSidebar />
              <main className="h-screen w-full">
                <SidebarTrigger variant="outline" className="p-4" />
                {children}
              </main>
            </TRPCReactProvider>
            <Toaster position="bottom-right" richColors />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
